spring:
  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      sensitive: false
---
spring:
  profiles: sqlserver-local
  datasource:
    url: "jdbc:sqlserver://springprimarydemo.database.windows.net:1433;database=u3b3afa7779b;Encrypt=true;TrustServerCertificate=false;HostNameInCertificate=*.database.windows.net;loginTimeout=30"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dataSourceProperties.ColumnEncryptionSetting: "Enabled"
    username: <DB USER>
    password: <DB PASSWORD>

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

microsoft:
  vault: #springdemosp
    clientId: <VAULT SP ClientID>
    clientSecret: <VAULT SP Client Secret>

---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost/music"
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

---
spring:
  profiles: postgres
  datasource:
    url: "jdbc:postgresql://localhost/music"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect

---
spring:
  profiles: mongodb
  data:
    mongodb:
      uri: mongodb://

